# Model configuration for a MFCN model
defaults:
  - _self_            
  - /heatmap: multi_task 

name: MFCN
load: ${..load_model}  # load model from checkpoint
save: ${..save_model}  # save model to checkpoint

weight_path: checkpoints/${..experiment_name}.pth
save_path: checkpoints/${..experiment_name}.pth
image_size: ${image_size}
mask_shape: ${mask_shape}
freeze: true


params:
  learning_rate: 0.0001
  batch_size: ${...batch_size}           # duplicated on purpose; you can omit if you prefer
  epochs: 30
  lambda_seg: 0.5       # formerly LAMBDA_VISUAL