# Model configuration for a deit_tiny model
defaults:
  - _self_            
  - /heatmap: multi_task 

name: deit_tiny
load: ${..load_model}  # load model from checkpoint
save: ${..save_model}  # save model to checkpoint

weight_path: checkpoints/multi_task_model.pth
image_size: ${image_size}
mask_shape: ${mask_shape}


params:
  learning_rate: 5e-4
  batch_size: ${..batch_size}           # duplicated on purpose; you can omit if you prefer
  epochs: 20
  lambda_visual: 0.2       # formerly LAMBDA_VISUAL