# Model configuration for a CNN model
defaults:
  - _self_            
  - /heatmap: gradcam_resnet

name: resnet
load: ${..load_model}  # load model from checkpoint
save: ${..save_model}  # save model to checkpoint
kernel_size: 7

weight_path: checkpoints/stored/resnet_16_20_UpperRight_config_upper_right_td2tpc71.pth
save_path: checkpoints/
image_size: ${image_size}
mask_shape: ${mask_shape}
freeze: true
pretrained: false # whether to use generic pretrained weights

params:
  learning_rate: 0.0001
  batch_size: ${...batch_size}           # duplicated on purpose; you can omit if you prefer
  epochs: 20