

numbers: ["UpperRight",7]
valid_range: [1001, 3000]
bounds: [-1, 11, -1, 11]
arcs_folder: ${hydra:runtime.cwd}/MSH/MSH/results/
coordinates_folder: ${hydra:runtime.cwd}/MSH/MSH/instances/
output_folder: ${hydra:runtime.cwd}/data/plots/

## for mask
mask_output_folder: ${hydra:runtime.cwd}/data/MSH/
special: ""

## for test_train
mask_split_output_folder: ${hydra:runtime.cwd}/data/
train_ratio: 0.75
random_state: 123

# background_image: data/fond/MTL.png