
java_parent: "/cvmfs/restricted.computecanada.ca/easybuild/software/2023/Core/gurobi/12.0.1"
java_lib: "${solver.java_parent}/lib"
java_bin: "${solver.java_parent}/bin"


program_name: "main.Main_customCosts"
config_name: "configurationCustomCosts2.xml"
org_config: "1"
custom_args:
  - "-Xmx14000m"
  - "-Djava.library.path=${solver.java_lib}"
  - "-cp"
  - "bin:${solver.java_lib}/gurobi.jar"




source_folder: "MSH/MSH"
bin_folder: "bin"
instance_folder: "instances/"
result_folder: "results/"
plot_output_folder: "output/test/"
