
java_parent: "${env:EBROOTGUROBI}"
java_lib: "${solver.java_parent}/lib"
java_bin: "${solver.java_parent}/bin"


program_name: "main.Main_customCosts"
config_name: "configurationCustomCosts2.xml"

custom_args:
  - "-Xmx14000m"
  - "-Djava.library.path=${solver.java_lib}"
  - "-cp"
  - "bin:${solver.java_lib}/gurobi.jar"


config: "CustomCosts" # suffix for the result folder
org_config: "1"

source_folder: "MSH/MSH"
bin_folder: "bin"
instance_folder: "instances/"
result_folder: "results/"
plot_output_folder: "output/test/"

plot: false