# Benchmark configuration for VRP MLP training
arcs_original: "MSH/MSH/results/configuration1/"
arcs_modified: "MSH/MSH/results/configuration2/"
coords: "MSH/MSH/instances/"
epochs: 5
batch_size: 32
lr: 0.001
hidden_dims: []
train_split: 0.8
seed: 42
