# @package _global_
arcs_folder: ${hydra:runtime.cwd}/MSH/MSH/results/
coordinates_folder: ${hydra:runtime.cwd}/MSH/MSH/instances/
output_folder: ${hydra:runtime.cwd}/data/plots_modified2/
valid_range: [1,80]
numbers: [8]