# @package _global_
arcs_folder: ${hydra:runtime.cwd}/MSH/MSH/results_modified/
coordinates_folder: ${hydra:runtime.cwd}/MSH/MSH/instances/
output_folder: ${hydra:runtime.cwd}/data/plots_modified2/
valid_range: [5,6]
numbers: [7]